runtime: go111

automatic_scaling:
  min_idle_instances: automatic   # idle状態にあるインスタンスの最小値
  max_idle_instances: 1                 # idle状態にあるインスタンスの最大値
  min_pending_latency: 3000ms  # リクエストを処理するまでに許される待ち時間の最小
  max_pending_latency: automatic

# チャネルシークレットとチャネルアクセストークンの環境変数
includes:
- secret.yaml

# use https
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
